version: '3.8'

services:
  flask:
    image: flask:loan_and_returns
    build: .
    volumes:
      - ./flask:/flask
    environment:
       TZ: America/Fortaleza
    restart: always
    ports:
      - "4000:80"
